def count_nucleotides(dna):
    a = 0
    c = 0
    g = 0
    t = 0
    for i in range(len(dna)):
        if dna[i] == "A":
            a += 1
        elif dna[i] == "C":
            c += 1
        elif dna[i] == "G":
            g += 1
        elif dna[i] == "T":
            t += 1
    print(a, c, g, t)


count_nucleotides("AGCCATCCACGGAATAGGCCTCTATACGTAGCCTCCGGACATGAGACGCCCTACAAGAGTATCAAATGTCGCTCACCATGGCCCCAACCAACCAACAGCCCCACCTCTAATGGTAGCAATCCTCACATGTAGATCACGGGCAGGAGCCCTACACTTCATAGTACTAGTAGAGGGACGGCGATAAGGGTTCTCTTCTGGTCTAAAGGCCAAGGCGGATTGCCACGCTGGTGGAAGGGGATAGCGGTCAGCACTTAGCCGCGGGTCAACCGGTCTGTAGGCGGTATCAGACATAAGCGTTCGCCCCCCCGATTGGCGAACGATTCGGAGTTTGGAACGCCTAAGGATGCGCTCGGAAACGGAGACTTATGATAAATTAGTTGCTCATTATAATATCAGGTGAGGCGGCCGCCGGACACTGATTAAACTATGTTGTTTAGAGGCATGTCTCGGAGGAATGCGACCGTCAAGCGATTGCGGAACCCGAGGTATGAACTGAGTCTGAACTCAAAGTGTTAGGAGTAAGGTGATATGACCAGACTTGGAGCCTGCCAGGTTCAGCTGACAGCAGGCTCTCGGCAGAGCTCATTGAACCGTAGAGACCTGCACGGCGAGAAAATCTGGGTGGCCGAAGACCTTCGGACGTCCGGCATTAAACATCCAGATGCTGGTATGAAGCCTTCAGCTAATTACTACGCTAACGTAGAGCGAAGGTCATTGAAAAGCCCTATCATCGCATCGTCCTTCGTGATCAGTAAAAAACAACAGCGAAAGGTTAAGGCCCAGCATGCGTCTGCTGACCCTCGATCTGTATTGCCAGTTTGAGAAGTCTGCCTTAAGTACCAGCTAGCACTCACCCCAGTTCTCTCAGTTAATTACAATGTCCTTGATACACCGTTCGAGGCAT")
