def dna_to_rna(dna):
    output = ""
    for i in range(len(dna)):
        if dna[i] == "T":
            output = output + "U"
        else:
            output = output + dna[i]
    print(output)


dna_to_rna("CTCGCATTCTCAGGCCCTTCCTAGATTGACATATAATCGCTGAACGCTCGTAAGCGGTGTGCACGTCATACACAAGGATGCGACGACGGTAACAGACACTTAGGCAATCAGTGGGCAAGATATCACGGAGTAAGGCTTTGGCAAACCGCGAGCCTTCGAGTGCTGAAATGTAAAGGTTCAAAAAGAACAAGTACCTTGAAGGACGCACGCCAGTGTTCGTTGCGAGTCTAAATAGCCCCCATTTACAGACTCGCAGTATTAGACTTGTCCCGTTAATCTGGGATGGGGTTATTATCGGAGGATCGAGTTTGCACTCGGTATCTAATGGCTACAGTAGTTGATTGCGGTAATTTTGCGTAACGGATAACCGGAATGAATGTGACCAAAGGACCGCTGTCTGCCCCGACTCATGGGACACGGCCTTCATCCGCCCTATAACTCTACGCAAGGAACTAGTCCGGAGGGCCTCCATGCGCGTTAGTGGGCAAAAGGACAGGTTTGGATCCCTACCACAAAGTCGGGTCACAACGTTAATAACTGGGATCCTCGAAGGCTACCACAATTCTCTTCTTGAATAGGGCTTGTCATGATTGAACGCTAAGTGCGAGAAAACGCAAGACAGTTACCTGCCCCTTTCGAGGGTTCCCTACGGTGGGACGATACAACGATACGAAAGTCGATGTTGGAAGTGGACCAGGCCGTCACGGTGGCAAATACGGTTTTATGATAAGTCGCACTTAGATGTAACGCTCCTTCACGACACGAGTACTCCTCTGTAGGAGTTTGCCCGCTACGGTCGCATCGCGACTCGTTGCTGCGACCCGCGAATCTAGGGGTCCAACATAAACAGCCTGCTCGCGAGCGAATCTTAGCCGCGAAGCTTAACGGGTCTAGGTTACGAACTAAGGATATGAGGGCATAATTCCAACTCTCGGGTCGTTTTTCAGAAGGGAGTTTAACCGGTCCCCGTACGAACAGTTCATA")
